## 폐암 수술 환자의 생존율 데이터 분석

In [1]:
# 필요한 라이브러리
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [6]:
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장
x_data = np.array(Data_set[:, 0:17], dtype=np.float64)
y_data = np.array(Data_set[:, 17], dtype=np.float64).reshape(470,1)

In [7]:
print(x_data.shape, y_data.shape)

(470, 17) (470, 1)


In [8]:
# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float64, shape=[None, 17])
Y = tf.placeholder(tf.float64, shape=[None, 1])

In [9]:
# Layer 1의 웨이트 W와 바이어스 b의 값을 임의로 정함 
W1 = tf.Variable(tf.random_normal([17,30], dtype=tf.float64)) 
b1 = tf.Variable(tf.random_normal([30], dtype=tf.float64))
L1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1))

### 아래와 같이 하면 cost 값이 nan 이 됨

In [10]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,1], dtype=tf.float64)) 
b2 = tf.Variable(tf.random_normal([1], dtype=tf.float64))
hypo = tf.sigmoid(tf.add(tf.matmul(L1, W2), b2))

In [11]:
# Binary Cross Entropy
learning_rate = 0.1
cost = tf.reduce_mean(-Y * tf.log(hypo) - (1.-Y) * tf.log(1.-hypo))

In [12]:
predicted = tf.cast(hypo > 0.5, dtype=tf.float64)
accuracy = tf.reduce_sum(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

In [13]:
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [14]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(10):
    _, cost_val, acc_val = sess.run([train, cost, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("step=%d, cost_val=%.4f, accuracy: %.4f" % (epoch + 1, cost_val, acc_val))

step=1, cost_val=nan, accuracy: 73.0000
step=2, cost_val=nan, accuracy: 400.0000
step=3, cost_val=nan, accuracy: 400.0000
step=4, cost_val=nan, accuracy: 400.0000
step=5, cost_val=nan, accuracy: 400.0000
step=6, cost_val=nan, accuracy: 400.0000
step=7, cost_val=nan, accuracy: 400.0000
step=8, cost_val=nan, accuracy: 400.0000
step=9, cost_val=nan, accuracy: 400.0000
step=10, cost_val=nan, accuracy: 400.0000


In [21]:
sess.close()

### nan을 피하려면 다음과 같이 하여야 함

In [22]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,1], dtype=tf.float64)) 
b2 = tf.Variable(tf.random_normal([1], dtype=tf.float64))
hypo = tf.add(tf.matmul(L1, W2), b2)

In [27]:
# Binary Cross Entropy
learning_rate = 0.1
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=hypo, labels=Y))

In [28]:
predicted = tf.cast(hypo > 0, dtype=tf.float64)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float64))

In [29]:
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [33]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(20):
    _, cost_val, acc_val = sess.run([train, cost, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("step=%d, cost_val=%.4f, accuracy: %.4f" % (epoch + 1, cost_val, acc_val))

step=1, cost_val=58.2431, accuracy: 0.6277
step=2, cost_val=111.5739, accuracy: 0.1511
step=3, cost_val=60.9688, accuracy: 0.8511
step=4, cost_val=110.1026, accuracy: 0.8511
step=5, cost_val=139.2158, accuracy: 0.8511
step=6, cost_val=153.6611, accuracy: 0.8511
step=7, cost_val=157.1180, accuracy: 0.8511
step=8, cost_val=152.2215, accuracy: 0.8511
step=9, cost_val=141.0324, accuracy: 0.8511
step=10, cost_val=125.1343, accuracy: 0.8511
step=11, cost_val=105.7110, accuracy: 0.8511
step=12, cost_val=83.6503, accuracy: 0.8511
step=13, cost_val=59.6170, accuracy: 0.8511
step=14, cost_val=33.9817, accuracy: 0.8511
step=15, cost_val=10.3022, accuracy: 0.7660
step=16, cost_val=122.4836, accuracy: 0.1574
step=17, cost_val=94.0483, accuracy: 0.1660
step=18, cost_val=10.6280, accuracy: 0.7574
step=19, cost_val=24.9501, accuracy: 0.8298
step=20, cost_val=37.2832, accuracy: 0.8511


### 평가

In [34]:
acc = sess.run(accuracy, feed_dict = {X: x_data, Y: y_data})
print("Accuracy: %.4f" % acc)

Accuracy: 0.8511


### 분석

In [35]:
W1_, W2_, b1_, b2_ = sess.run([W1, W2, b1, b2])

In [36]:
def ReLU(x):
    return x * (x > 0)
def sigmoid(x):
    return 1./(1. + np.e**(-x))

In [37]:
b1_

array([-0.59640411, -1.72213433,  0.50589363, -1.81112216,  0.48397328,
        1.58679519, -0.00832799, -1.85492855,  1.25208003, -1.4175388 ,
        0.48488214, -1.37162592, -0.1953683 ,  0.32232278,  1.04495816,
        0.16088034, -0.83244772,  0.31716335,  0.05333922,  1.89894556,
        1.57152997, -0.98126552,  0.50642814, -0.02770568, -0.26298234,
       -1.5776204 , -0.30035346, -0.6813579 , -1.18515155, -2.17332714])

In [38]:
L1_ = ReLU(np.matmul(x_data[0,:].reshape(1,17), W1_) + b1_)
L1_

array([[321.38458104,  56.07317988, 186.52442246,  -0.        ,
         50.3599364 , 585.23276281, 148.24917924,  -0.        ,
         -0.        ,  -0.        ,  -0.        ,  -0.        ,
         48.08386349,  49.72062279,  -0.        ,  -0.        ,
        698.90993225, 662.66309623,  -0.        ,  -0.        ,
         -0.        , 106.37784347,  -0.        ,  -0.        ,
         -0.        ,  49.00490234,   5.78512114,  -0.        ,
         -0.        ,  -0.        ]])

In [39]:
L2_ = np.matmul(L1_, W2_) + b2_
H = sigmoid(L2_)
print(L2_[0].item(), H[0].item())

-416.6203530057555 1.1589898724811117e-181


In [40]:
y_data[0].item()

0.0