## 폐암 수술 환자의 생존율 데이터 분석

In [1]:
# 필요한 라이브러리
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [4]:
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장
x_data = np.array(Data_set[:, 0:17], dtype=np.float32)
y_data = np.array(Data_set[:, 17], dtype=np.float32).reshape(470,1)

In [5]:
print(x_data.shape, y_data.shape)

(470, 17) (470, 1)


In [6]:
# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float32, shape=[None, 17])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [7]:
# Layer 1의 웨이트 W와 바이어스 b의 값을 임의로 정함 
W1 = tf.Variable(tf.random_normal([17,30], dtype=tf.float32)) 
b1 = tf.Variable(tf.random_normal([30], dtype=tf.float32))
L1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1))

### 아래와 같이 하면 cost 값이 nan 이 됨

In [8]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,1], dtype=tf.float32)) 
b2 = tf.Variable(tf.random_normal([1], dtype=tf.float32))
hypo = tf.sigmoid(tf.add(tf.matmul(L1, W2), b2))

In [9]:
# Binary Cross Entropy
learning_rate = 0.1
cost = tf.reduce_mean(-Y * tf.log(hypo) - (1.-Y) * tf.log(1.-hypo))

In [12]:
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_sum(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [13]:
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [14]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(10):
    _, cost_val, acc_val = sess.run([train, cost, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("step=%d, cost_val=%.4f, accuracy: %.4f" % (epoch + 1, cost_val, acc_val))

step=1, cost_val=nan, accuracy: 72.0000
step=2, cost_val=nan, accuracy: 400.0000
step=3, cost_val=nan, accuracy: 400.0000
step=4, cost_val=nan, accuracy: 400.0000
step=5, cost_val=nan, accuracy: 400.0000
step=6, cost_val=nan, accuracy: 400.0000
step=7, cost_val=nan, accuracy: 400.0000
step=8, cost_val=nan, accuracy: 400.0000
step=9, cost_val=nan, accuracy: 400.0000
step=10, cost_val=nan, accuracy: 400.0000


In [15]:
sess.close()

### nan을 피하려면 다음과 같이 하여야 함

In [16]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,1], dtype=tf.float32)) 
b2 = tf.Variable(tf.random_normal([1], dtype=tf.float32))
hypo = tf.add(tf.matmul(L1, W2), b2)

In [19]:
# Binary Cross Entropy
learning_rate = 0.1
cost = tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(logits=hypo, labels=Y))

In [20]:
predicted = tf.cast(hypo > 0, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [21]:
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [22]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(20):
    _, cost_val, acc_val = sess.run([train, cost, accuracy], feed_dict = {X: x_data, Y: y_data})
    print("step=%d, cost_val=%.4f, accuracy: %.4f" % (epoch + 1, cost_val, acc_val))

step=1, cost_val=108.6388, accuracy: 0.8511
step=2, cost_val=24.9926, accuracy: 0.7340
step=3, cost_val=454.2517, accuracy: 0.1489
step=4, cost_val=135.2872, accuracy: 0.1489
step=5, cost_val=48.6357, accuracy: 0.8511
step=6, cost_val=96.5640, accuracy: 0.8511
step=7, cost_val=127.7641, accuracy: 0.8511
step=8, cost_val=147.4855, accuracy: 0.8511
step=9, cost_val=158.5266, accuracy: 0.8511
step=10, cost_val=162.8943, accuracy: 0.8511
step=11, cost_val=162.1107, accuracy: 0.8511
step=12, cost_val=157.4555, accuracy: 0.8511
step=13, cost_val=149.8050, accuracy: 0.8511
step=14, cost_val=139.9702, accuracy: 0.8511
step=15, cost_val=129.0041, accuracy: 0.8511
step=16, cost_val=117.3709, accuracy: 0.8511
step=17, cost_val=105.2772, accuracy: 0.8511
step=18, cost_val=92.8469, accuracy: 0.8511
step=19, cost_val=80.1646, accuracy: 0.8511
step=20, cost_val=67.3548, accuracy: 0.8511


### 평가

In [23]:
acc = sess.run(accuracy, feed_dict = {X: x_data, Y: y_data})
print("Accuracy: %.4f" % acc)

Accuracy: 0.8511


### 분석

In [24]:
W1_, W2_, b1_, b2_ = sess.run([W1, W2, b1, b2])

In [25]:
def ReLU(x):
    return x * (x > 0)
def sigmoid(x):
    return 1./(1. + np.e**(-x))

In [26]:
b1_

array([-1.6488755 , -1.6936338 ,  0.22648185,  2.2550836 ,  1.1665237 ,
        1.6196547 ,  1.0274365 , -0.49741533, -0.18586   , -1.4479506 ,
        1.6215065 ,  0.864628  ,  1.5465599 ,  0.545661  , -0.5757081 ,
        0.08227626, -0.58398473,  0.21234226, -0.01111865, -0.04562002,
       -0.68967175, -1.4038917 , -0.5711855 ,  0.3626712 , -1.8472904 ,
       -0.571195  ,  1.4901446 , -3.0709605 ,  1.1785848 ,  0.8443789 ],
      dtype=float32)

In [27]:
L1_ = ReLU(np.matmul(x_data[0,:].reshape(1,17), W1_) + b1_)
L1_

array([[ -0.     ,  -0.     ,  -0.     ,  -0.     ,  -0.     ,  -0.     ,
         48.93174,  -0.     ,  -0.     ,  -0.     , 270.80792, 144.8055 ,
         -0.     ,  -0.     ,  -0.     ,  -0.     ,  -0.     ,  -0.     ,
         -0.     ,  -0.     ,  -0.     ,  -0.     ,  -0.     , 529.7488 ,
         -0.     ,  -0.     ,  -0.     ,  -0.     , 262.80197, 262.55408]],
      dtype=float32)

In [28]:
L2_ = np.matmul(L1_, W2_) + b2_
H = sigmoid(L2_)
print(L2_[0].item(), H[0].item())

-489.7164306640625 0.0


C:\Users\EZEN\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: overflow encountered in power
  after removing the cwd from sys.path.


In [29]:
y_data[0].item()

0.0