## 폐암 수술 환자의 생존율 데이터 분석

In [1]:
# 필요한 라이브러리
import numpy as np
import tensorflow as tf
tf.__version__

'2.0.0'

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [3]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 0
np.random.seed(seed)
tf.random.set_seed(seed)

In [4]:
# 준비된 수술 환자 데이터를 불러들임
Data_set = np.loadtxt("dataset/ThoraricSurgery.csv", delimiter=",")
Data_set

array([[293.  ,   1.  ,   3.8 , ...,   0.  ,  62.  ,   0.  ],
       [  1.  ,   2.  ,   2.88, ...,   0.  ,  60.  ,   0.  ],
       [  8.  ,   2.  ,   3.19, ...,   0.  ,  66.  ,   1.  ],
       ...,
       [406.  ,   6.  ,   5.36, ...,   0.  ,  62.  ,   0.  ],
       [ 25.  ,   8.  ,   4.32, ...,   0.  ,  58.  ,   1.  ],
       [447.  ,   8.  ,   5.2 , ...,   0.  ,  49.  ,   0.  ]])

In [5]:
# 환자의 기록과 수술 결과를 X와 Y로 구분하여 저장
X = Data_set[:, 0:17]
Y = Data_set[:, 17]
X.shape, Y.shape

((470, 17), (470,))

In [6]:
# 딥러닝 모델 설정
hidden = Dense(30, input_shape=(17,), activation='relu', name='Hidden_Layer')
output = Dense(1, activation='sigmoid', name='Output_Layer')
model = Sequential()
model.add(hidden)
model.add(output)
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Hidden_Layer (Dense)         (None, 30)                540       
_________________________________________________________________
Output_Layer (Dense)         (None, 1)                 31        
Total params: 571
Trainable params: 571
Non-trainable params: 0
_________________________________________________________________


In [7]:
# 딥러닝 환경 설정 (오차함수, 최적화함수)
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [8]:
# 딥러닝 실행
model.fit(X, Y, epochs=20, batch_size=10)

Train on 470 samples
Epoch 1/20
470/470 [==============================] - 2s 4ms/sample - loss: 3.8373 - accuracy: 0.6489
Epoch 2/20
470/470 [==============================] - 0s 267us/sample - loss: 0.6170 - accuracy: 0.8298
Epoch 3/20
470/470 [==============================] - 0s 267us/sample - loss: 0.4939 - accuracy: 0.8447
Epoch 4/20
470/470 [==============================] - 0s 280us/sample - loss: 0.5024 - accuracy: 0.8319
Epoch 5/20
470/470 [==============================] - 0s 314us/sample - loss: 0.4672 - accuracy: 0.8404
Epoch 6/20
470/470 [==============================] - 0s 265us/sample - loss: 0.4807 - accuracy: 0.8511
Epoch 7/20
470/470 [==============================] - 0s 269us/sample - loss: 0.4820 - accuracy: 0.8383
Epoch 8/20
470/470 [==============================] - 0s 276us/sample - loss: 0.4812 - accuracy: 0.8468
Epoch 9/20
470/470 [==============================] - 0s 316us/sample - loss: 0.4751 - accuracy: 0.8468
Epoch 10/20
470/470 [========================

In [9]:
# 결과 출력
# evaluate() returns the loss value & metrics values for the model 
print("\n Accuracy: %.4f" % (model.evaluate(X, Y, verbose=2))[1])

470/1 - 0s - loss: 0.9498 - accuracy: 0.8532

 Accuracy: 0.8532


### Weight와 bias를 구하는 방법

In [10]:
hidden.get_config()

{'name': 'Hidden_Layer',
 'trainable': True,
 'batch_input_shape': (None, 17),
 'dtype': 'float32',
 'units': 30,
 'activation': 'relu',
 'use_bias': True,
 'kernel_initializer': {'class_name': 'GlorotUniform',
  'config': {'seed': None}},
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 'kernel_regularizer': None,
 'bias_regularizer': None,
 'activity_regularizer': None,
 'kernel_constraint': None,
 'bias_constraint': None}

In [11]:
hl = hidden.get_weights()

In [12]:
type(hl)

list

In [13]:
len(hl[0]), len(hl[1])

(17, 30)

In [14]:
W1 = hl[0]
W1.shape

(17, 30)

In [15]:
b1 = W1[1]
b1

array([-0.20977446, -0.1037964 , -0.1605466 , -0.25685525, -0.27460045,
        0.1918003 ,  0.06241258,  0.3673455 ,  0.25394616, -0.2560622 ,
       -0.25761172,  0.07367649, -0.23814453, -0.02003992,  0.29244506,
       -0.20140937, -0.35186014,  0.06906801,  0.01232258,  0.21800292,
        0.05997312, -0.34817117,  0.2828323 , -0.1270954 , -0.00245204,
       -0.16273206, -0.28886884, -0.1004855 , -0.3074081 , -0.36045903],
      dtype=float32)

In [16]:
output.get_config()

{'name': 'Output_Layer',
 'trainable': True,
 'dtype': 'float32',
 'units': 1,
 'activation': 'sigmoid',
 'use_bias': True,
 'kernel_initializer': {'class_name': 'GlorotUniform',
  'config': {'seed': None}},
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},
 'kernel_regularizer': None,
 'bias_regularizer': None,
 'activity_regularizer': None,
 'kernel_constraint': None,
 'bias_constraint': None}

In [17]:
output.get_weights()

[array([[ 0.03103479],
        [-0.40789023],
        [ 0.3093211 ],
        [ 0.21061262],
        [ 0.12422135],
        [ 0.01136309],
        [-0.4622881 ],
        [ 0.31394702],
        [-0.04393003],
        [-0.09966528],
        [ 0.3176729 ],
        [ 0.11698484],
        [-0.43491066],
        [ 0.29235536],
        [-0.34820223],
        [ 0.38379648],
        [-0.2646584 ],
        [ 0.11770991],
        [-0.34917378],
        [-0.3086719 ],
        [ 0.42861092],
        [ 0.34584683],
        [-0.393825  ],
        [ 0.12181813],
        [-0.04958315],
        [ 0.42037734],
        [ 0.3208077 ],
        [ 0.22253889],
        [ 0.22082669],
        [-0.19559163]], dtype=float32), array([-0.00844426], dtype=float32)]

In [18]:
W2 = output.get_weights()[0]
b2 = output.get_weights()[1]

In [19]:
W2.shape

(30, 1)

In [20]:
b2

array([-0.00844426], dtype=float32)