# 다중 선형회귀
## 보스톤 집값

In [1]:
import numpy as np
import pandas as pd
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
from sklearn.model_selection import train_test_split

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
# seed 값 생성
seed = 0
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
df = pd.read_csv("dataset/housing.csv", delim_whitespace=True, header=None)
dataset = df.values
x_data = np.array(dataset[:,0:13], dtype=np.float64)
y_data = np.array(dataset[:,13], dtype=np.float64).reshape(-1,1)
print(x_data.shape, y_data.shape)

(506, 13) (506, 1)


In [4]:
X_train, X_test, Y_train, Y_test = train_test_split(x_data, y_data, test_size=0.3, 
                                                    random_state=seed)

In [20]:
# 입력 값을 플레이스 홀더에 저장
X = tf.placeholder(tf.float64, shape=[None, 13])
Y = tf.placeholder(tf.float64, shape=[None, 1])

In [21]:
# Layer 1
W1 = tf.Variable(tf.random_normal([13,30], dtype=tf.float64)) 
b1 = tf.Variable(tf.random_normal([30], dtype=tf.float64))
#L1 = tf.nn.relu(tf.add(tf.matmul(X, W1), b1))
L1 = tf.add(tf.matmul(X, W1), b1)

In [22]:
# Layer 2
W2 = tf.Variable(tf.random_normal([30,6], dtype=tf.float64)) 
b2 = tf.Variable(tf.random_normal([6], dtype=tf.float64))
#L2 = tf.nn.relu(tf.add(tf.matmul(L1, W2), b2))
L2 = tf.add(tf.matmul(L1, W2), b2)

In [23]:
# Layer 3
W3 = tf.Variable(tf.random_normal([6,1], dtype=tf.float64)) 
b3 = tf.Variable(tf.random_normal([1], dtype=tf.float64))
hypo = tf.add(tf.matmul(L2, W3), b3)

In [24]:
# Mean Squared Error
cost = tf.reduce_mean(tf.square(Y - hypo))

In [25]:
learning_rate = 0.1
train = tf.train.AdamOptimizer(learning_rate).minimize(cost)

In [26]:
# 학습
sess = tf.Session()
sess.run(tf.global_variables_initializer())

for epoch in range(2001):
    sess.run(train, feed_dict = {X: X_train, Y: Y_train})
    if epoch % 100 == 0:
        cost_val = sess.run(cost, feed_dict = {X: X_train, Y: Y_train})
        print("step=%d, \tcost_val=%.5f" % (epoch + 1, cost_val))
    
W1_, W2_, W3_, b1_, b2_, b3_ = sess.run([W1, W2, W3, b1, b2, b3])

step=1, 	cost_val=4227517.51872
step=101, 	cost_val=1799.22513
step=201, 	cost_val=419.25091
step=301, 	cost_val=243.56352
step=401, 	cost_val=168.42149
step=501, 	cost_val=134.73479
step=601, 	cost_val=116.09776
step=701, 	cost_val=102.74672
step=801, 	cost_val=91.96544
step=901, 	cost_val=83.09260
step=1001, 	cost_val=75.86713
step=1101, 	cost_val=70.05712
step=1201, 	cost_val=65.41973
step=1301, 	cost_val=61.71713
step=1401, 	cost_val=58.73296
step=1501, 	cost_val=56.28191
step=1601, 	cost_val=54.21331
step=1701, 	cost_val=52.41034
step=1801, 	cost_val=50.78651
step=1901, 	cost_val=49.28067
step=2001, 	cost_val=47.85169


In [27]:
X_test[0,:], Y_test[0]

(array([6.7240e-02, 0.0000e+00, 3.2400e+00, 0.0000e+00, 4.6000e-01,
        6.3330e+00, 1.7200e+01, 5.2146e+00, 4.0000e+00, 4.3000e+02,
        1.6900e+01, 3.7521e+02, 7.3400e+00]), array([22.6]))

In [28]:
hypo_val = sess.run(hypo, feed_dict = {X: X_test[0,:].reshape(1,13)})
hypo_val[0].item()

18.31252807702382

In [29]:
hypo_val = sess.run(hypo, feed_dict = {X: X_test[10,:].reshape(1,13)})
hypo_val[0].item()

3.044841093939292

In [30]:
real = float(Y_test[0].item())
type(Y_test[0]), type(Y_test[0].item()), type(real)

(numpy.ndarray, float, float)

In [31]:
for i in range(10):
    hypo_val = sess.run(hypo, feed_dict = {X: X_test[i,:].reshape(1,13)})
    real = float(Y_test[i].item())
    print("실제가격: {:.3f}, 예상가격: {:.3f}".format(real, hypo_val[0].item()))

실제가격: 22.600, 예상가격: 18.313
실제가격: 50.000, 예상가격: 26.754
실제가격: 23.000, 예상가격: 30.291
실제가격: 8.300, 예상가격: 17.480
실제가격: 21.200, 예상가격: 21.023
실제가격: 19.900, 예상가격: 24.397
실제가격: 20.600, 예상가격: 20.888
실제가격: 18.700, 예상가격: 24.319
실제가격: 16.100, 예상가격: 13.770
실제가격: 18.600, 예상가격: 14.886


In [14]:
def ReLU(x):
    return x * (x > 0)

In [15]:
L1_ = ReLU(np.matmul(X_test[0,:].reshape(1,13), W1_) + b1_)
L1_

array([[1026.23829698,   -0.        ,  171.87386865,   -0.        ,
         910.37609293,   -0.        ,   -0.        ,  385.50032964,
          -0.        ,   -0.        ,  481.81291107,   -0.        ,
          -0.        ,   -0.        ,   -0.        ,   -0.        ,
        1504.30751992,   -0.        ,   -0.        ,   -0.        ,
          -0.        ,   -0.        ,   -0.        ,  562.77518204,
          -0.        ,  311.44563972,   -0.        ,   -0.        ,
         224.98064201,   -0.        ]])

In [19]:
L2_ = ReLU(np.matmul(L1_, W2_) + b2_)
L2_

array([[-0., -0., -0., -0., -0., -0.]])

In [20]:
H = np.matmul(L2_, W3_) + b3_
H

array([[22.28272214]])