## 다층 퍼셉트론 - XOR - Tensorflow 1.x

In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [14]:
# 실행할 때마다 같은 결과를 출력하기 위한 seed 값 설정
seed = 123
np.random.seed(seed)
tf.set_random_seed(seed)

In [3]:
# x, y의 데이터 값
x_data = np.array([[0, 0],[0, 1],[1, 0],[1, 1]]) 
y_data = np.array([0, 1, 1, 0])
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4,)


array([0, 1, 1, 0])

In [4]:
y_data = y_data.reshape(4,1)
print(x_data.shape, y_data.shape)
y_data

(4, 2) (4, 1)


array([[0],
       [1],
       [1],
       [0]])

In [5]:
X = tf.placeholder(tf.float32, [None, 2])
Y = tf.placeholder(tf.float32, [None, 1])

In [6]:
# Layer 1
W1 = tf.Variable(tf.random_normal([2, 2]), dtype=tf.float32)
b1 = tf.Variable(tf.random_normal([2]), dtype=tf.float32)
L1 = tf.sigmoid(tf.matmul(X, W1) + b1)

In [7]:
# Layer 2
W2 = tf.Variable(tf.random_normal([2, 1]), dtype=tf.float32)
b2 = tf.Variable(tf.random_normal([1]), dtype=tf.float32)
hypo = tf.sigmoid(tf.matmul(L1, W2) + b2)

In [8]:
# Cost - Binary Cross Entropy
cost = -tf.reduce_mean(Y * tf.log(hypo) + (1.-Y) * tf.log(1.-hypo))

In [16]:
# Optimizer - Adam
lr = 0.1
train = tf.train.AdamOptimizer(learning_rate=lr).minimize(cost)

In [10]:
# Accuracy 계산
predicted = tf.cast(hypo > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [17]:
# 학습
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    for step in range(10001):
        _, cost_val = sess.run([train, cost], feed_dict={X: x_data, Y: y_data})
        if step % 1000 == 0:
            print(step, cost_val)
            
    # Accuracy report
    h, p, a = sess.run([hypo, predicted, accuracy], feed_dict={X: x_data, Y: y_data}) 
    print(f"\nHypothesis:\n{h} \nPredicted:\n{p} \nAccuracy:\n{a}")
    
    # Weight, bias
    W1_, b1_, W2_, b2_ = sess.run([W1, b1, W2, b2])
    print(f"\nW1:\n{W1_} \nb1:\n{b1_} \nW2:\n{W2_}\nb1:\n{b2_}")

0 0.7033546
1000 0.34680158
2000 0.3466391
3000 0.346602
4000 0.34658813
5000 0.3465813
6000 0.34657827
7000 0.3465762
8000 0.34657523
9000 0.3465744
10000 0.34657425

Hypothesis:
[[5.0000072e-01]
 [4.9999973e-01]
 [9.9999928e-01]
 [4.1723251e-07]] 
Predicted:
[[1.]
 [0.]
 [1.]
 [0.]] 
Accuracy:
0.5

W1:
[[18.690361  19.531244 ]
 [ 5.2994647 -8.157976 ]] 
b1:
[-21.826498 -16.547342] 
W2:
[[-16.485106]
 [ 15.602318]]
b1:
[1.3868048e-06]
